# Workflow to initialise the solution in GitHub from an existing solution in CDS
name: initialise-repo

on:
  workflow_dispatch:
    inputs:
      applicationId:
        description: "Application Id"
        required: true
        default: "f0a39d99-08df-492d-9c84-ecc22aaa064a"
      tenantId:
        description: "Tenant Id"
        required: true
        default: '6698ac31-e602-4f64-ac1f-472ae585c006'          
      environmentUrl:
        description: "Source Environment URL"
        required: true
        default: "https://dreamingincrm.crm6.dynamics.com"
      solution:
        description: "Solution to export"
        required: true
        default: "GitHubSolution"
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - id: who-am-i
        uses: microsoft/powerplatform-actions/who-am-i@main
        with:
          environment-url: ${{ env.environmentUrl }}        
          app-id: ${{ env.applicationId }}
          client-secret: ${{ secrets.dataversesecret }}
          tenant-id: ${{ env.tenantId }}

      - id: clone-solution
        uses: microsoft/powerplatform-actions/clone-solution@main
        with:
          environment-url: ${{ env.environmentUrl }}        
          app-id: ${{ env.applicationId }}
          client-secret: ${{ secrets.dataversesecret }}
          tenant-id: ${{ env.tenantId }}
          solution-name: ${{ github.event.inputs.solution }}
          target-folder: "./Solutions"

      - id: solution-version
        uses: mavrosxristoforos/get-xml-info@1.0
        with:
          xml-file: "Solutions/${{ github.event.inputs.solution }}/src/Other/Solution.xml"
          xpath: "//ImportExportXml/SolutionManifest/Version"

      - id: branch-name
        run: |
          echo "::set-output name=branchName::${{ github.event.inputs.solution }}_${{ steps.solution-version.outputs.info }}"

      - id: create-solution-branch
        uses: microsoft/powerplatform-actions/branch-solution@main
        with:
          solution-folder: "Solutions/${{ github.event.inputs.solution }}"
          solution-target-folder: "Solutions/${{ github.event.inputs.solution }}"
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          branch-name: ${{ steps.branch-name.outputs.branchName }}

      - uses: octokit/request-action@v2.x
        id: create_pr
        with:
          owner: "rajyraman"
          repo: ${{ github.repository }}
          route: POST /repos/:repo/pulls
          title: ${{ steps.branch-name.outputs.branchName }}
          head: ${{ steps.branch-name.outputs.branchName }}
          base: "main"
          maintainer_can_modify: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
