name: temp

on:
  workflow_dispatch:
    inputs:
      applicationId:
        description: "Application Id"
        required: true
        default: 'e605bea5-f749-4f51-8508-8c6891d9f8dc'
      tenantId:
        description: "Tenant Id"
        required: true
        default: '6698ac31-e602-4f64-ac1f-472ae585c006'        
      userName:
        description: "User Name"
        required: true
        default: 'actionsuser@dreamingincrm.onmicrosoft.com'        
      sourceEnvironmentUrl:
        description: "Environment URL"
        required: true
        default: 'https://dreamingincrm.crm6.dynamics.com'
      solutionType:
        description: "Managed or Unmanaged?"
        required: true
        default: 'Managed'
      solutionName:
        description: "Solution to import"
        required: true
        default: 'GitHubSolution'
      release:
        description: "Release?"
        required: true
        default: false        
jobs:
  build:
    runs-on: [self-hosted, windows, x64]
    env:
      timeZone: "AUS Eastern Standard Time"
    steps:
      - uses: actions/checkout@v2
        
      - id: who-am-i
        name: Connecting to ${{ env.environmentUrl }} as ${{ env.userName }}
        uses: microsoft/powerplatform-actions/who-am-i@main
        with:
          environment-url: ${{ github.event.inputs.sourceEnvironmentUrl }}
          app-id: ${{ github.event.inputs.applicationId }}
          client-secret: ${{ secrets.cds }}
          tenant-id: ${{ github.event.inputs.tenantId }}