name: temp

on:
  workflow_dispatch:
    inputs:
      applicationId:
        description: "Application Id"
        required: true
        default: 'e605bea5-f749-4f51-8508-8c6891d9f8dc'
      userName:
        description: "User Name"
        required: true
        default: 'actionsuser@dreamingincrm.onmicrosoft.com'        
      sourceEnvironmentUrl:
        description: "Environment URL"
        required: true
        default: 'https://dreamingincrm.crm6.dynamics.com'
      solutionType:
        description: "Managed or Unmanaged?"
        required: true
        default: 'Managed'
      solutionName:
        description: "Solution to import"
        required: true
        default: 'GitHubSolution'
      release:
        description: "Release?"
        required: true
        default: false        
jobs:
  build:
    runs-on: [self-hosted, windows, x64]
    env:
      timeZone: "AUS Eastern Standard Time"
    steps:
      - uses: actions/checkout@v2
        
      - id: who-am-i
        name: Connecting to ${{ env.environmentUrl }} as ${{ env.userName }}
        uses: microsoft/powerplatform-actions/who-am-i@465ec9b6d3336a846e5f7b3a5620e035e2f82331
        with:
          environment-url: ${{ github.event.inputs.sourceEnvironmentUrl }}
          user-name: ${{ github.event.inputs.userName }}
          password-secret: ${{ secrets.password }}
          
      - id: pack-solution
        name: Build ${{ env.solution }} as ${{ github.event.inputs.solutionType }} Solution
        uses: microsoft/powerplatform-actions/pack-solution@465ec9b6d3336a846e5f7b3a5620e035e2f82331
        with:
          solution-file: 'out/${{ github.event.inputs.solutionName }}.zip'
          solution-folder: 'Solutions/${{ github.event.inputs.solutionName }}/src'
          solution-type: ${{ github.event.inputs.solutionType }}
          
      - name: Debugging with tmate
        uses: mxschmitt/action-tmate@v3.3
